### PR TITLE
Bug fix gif

### LINKED ISSUE #199: Saving gif gives wrong\missing pallet colors
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
This original image
original-gif

when saving turns into this
bad-gif

looks like a color pallet issue

### Steps to Reproduce
```C#
Image.Load("original-gif.gif").Save("bad-gif.gif");
```

### System Configuration

- ImageSharp version: 1.0.0-alpha7-0031
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): win10 x64
- .NET Framework version: netcoreapp1.0 and net461
- Additional information:

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/JimBobSquarePants/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practise as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
This PR fixes #199 plus a couple of other issues I spotted during testing.

### CODE REVIEW

File: src/ImageSharp/Formats/Gif/GifEncoderCore.cs [hunk 1]
```diff
@@ -302,16 +312,10 @@ private void WriteGraphicalControlExtension<TPixel>(ImageFrame<TPixel> imageFram
         private void WriteGraphicalControlExtension<TPixel>(ImageBase<TPixel> image, IMetaData metaData, EndianBinaryWriter writer, int transparencyIndex)
             where TPixel : struct, IPixel<TPixel>
         {
-            // TODO: Check transparency logic.
```
Comment (dlemstra) [inline src/ImageSharp/Formats/Gif/GifEncoderCore.cs]: This logic seems to be gone because the `DisposalMethod` has been moved to `IMetaData`. Maybe you should make the DisposalMethod nullable so you can check if you can copy the value from the original. But I do wonder if this logic makes any sense though. We can probably just have `DisposalMethod.Unspecified` as the default.

File: src/ImageSharp/MetaData/ImageMetaData.cs [hunk 2]
```diff
@@ -116,14 +118,12 @@ public double VerticalResolution
...
-        /// <summary>
-        /// Gets or sets the frame delay for animated images.
-        /// If not 0, this field specifies the number of hundredths (1/100) of a second to
-        /// wait before continuing with the processing of the Data Stream.
-        /// The clock starts ticking immediately after the graphic is rendered.
-        /// </summary>
+        /// <inheritdoc/>
         public int FrameDelay { get; set; }
 
+        /// <inheritdoc/>
```
Comment (dlemstra) [inline src/ImageSharp/MetaData/ImageMetaData.cs]: Not sure why you want to use `inheritdoc` here but don't do it for the other fields. Think it's better to just put the comments here. Never seen `inheritdoc` do anything in the code completion.

File: src/ImageSharp/Formats/Gif/GifDecoderCore.cs [hunk 3]
```diff
@@ -332,6 +333,7 @@ private void ReadFrame()
         /// </summary>
         /// <param name="imageDescriptor">The <see cref="GifImageDescriptor"/>.</param>
         /// <param name="indices">The pixel array to write to.</param>
+        [MethodImpl(MethodImplOptions.AggressiveInlining)]
```
Comment (dlemstra) [inline src/ImageSharp/Formats/Gif/GifDecoderCore.cs]: Do we really need this?

File: src/ImageSharp/Formats/Gif/GifDecoderCore.cs [hunk 4]
```diff
@@ -506,14 +508,20 @@ private void RestoreToBackground(ImageBase<TPixel> frame)
...
         /// <summary>
-        /// Sets the frame delay in the metadata.
+        /// Sets the frames metadata.
         /// </summary>
         /// <param name="metaData">The meta data.</param>
-        private void SetFrameDelay(IMetaData metaData)
+        [MethodImpl(MethodImplOptions.AggressiveInlining)]
+        private void SetFrameMetaData(IMetaData metaData)
         {
             if (this.graphicsControlExtension != null && this.graphicsControlExtension.DelayTime > 0)
```
Comment (dlemstra) [inline src/ImageSharp/Formats/Gif/GifDecoderCore.cs]: You probably want to remove the second check from this if? You moved it inside already.

File: src/ImageSharp/Formats/Gif/GifEncoderCore.cs [hunk 5]
```diff
@@ -74,7 +79,13 @@ public void Encode<TPixel>(Image<TPixel> image, Stream stream)
             this.bitDepth = ImageMaths.GetBitsNeededForColorDepth(quality);
 
             // Quantize the image returning a palette.
-            QuantizedImage<TPixel> quantized = ((IQuantizer<TPixel>)this.Quantizer).Quantize(image, quality);
+            this.hasMultipleFrames = image.Frames.Any();
```
Comment (dlemstra) [inline src/ImageSharp/Formats/Gif/GifEncoderCore.cs]: I know this is correct but the statement looks confusing when you look at it the first time. Maybe you should call it `hasFrames` instead?

Comment (JimBobSquarePants) [inline src/ImageSharp/Formats/Gif/GifEncoderCore.cs]: Yeah, that's clearer, will do.

File: src/ImageSharp/MetaData/ImageMetaData.cs (hunk 2 above)
Comment (JimBobSquarePants) [inline src/ImageSharp/MetaData/ImageMetaData.cs]: Ugh, just realised that VS doesn't currently support intellisense based on inheritdoc. I don't want to stop using it though as it massively cuts down on errors duplicating XML docs and Wyam already supports it for our API docs. 

It looks like MVC are planning to use post processing to augment their XML output. I think we should follow suite. 
https://github.com/aspnet/Mvc/issues/928

File: src/ImageSharp/Formats/Gif/GifEncoderCore.cs (hunk 1 above)
Comment (JimBobSquarePants) [inline src/ImageSharp/Formats/Gif/GifEncoderCore.cs]: Original logic was incorrect. `DisposalMethod.Unspecified` is already the default and unless we are doing something crazy with the gif between decoding/encoding we should definitely copy the properties across. Devs have the power now to set each frame value independently should they choose.

File: src/ImageSharp/Formats/Gif/GifDecoderCore.cs (hunk 4 above)
Comment (JimBobSquarePants) [inline src/ImageSharp/Formats/Gif/GifDecoderCore.cs]: Yeah, good to remove.

File: src/ImageSharp/Formats/Gif/GifDecoderCore.cs (hunk 3 above)
Comment (JimBobSquarePants) [inline src/ImageSharp/Formats/Gif/GifDecoderCore.cs]: There's no harm in doing this. We want to inline as many small private methods as we can really.

**Comment by JimBobSquarePants** [comment]
Imma gonna merge this. It all works and any changes can be made internally.
